- type: job
  id: Chemist
  name: job-name-chemist
  description: job-description-chemist
  playTimeTracker: JobChemist
  setPreference: true
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 #10 hrs
  displayWeight: 60
  startingGear: ChemistGear
  icon: "JobIconChemist"
  supervisors: job-supervisors-chom
  access:
  - Captain
  accessGroups:
  - Command
  - AllAccess

- type: startingGear
  id: ChemistGear
  equipment:
    id: ChemistryPDA
    ears: ClothingHeadsetCommandingOfficer

- type: chameleonOutfit
  id: ChemistChameleonOutfit
  job: Chemist
  equipment:
    head: ClothingHeadHatBeretMedic
    mask: ClothingMaskSterile
    neck: ClothingNeckStethoscope
    outerClothing: ClothingOuterCoatLabChem
    gloves: ClothingHandsGlovesLatex
