- type: job
  id: FlagChemist
  name: job-name-flag-chemist
  description: job-description-flag-chemist
  playTimeTracker: JobFlagChemist
  setPreference: true
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 #10 hrs
  displayWeight: 60
  startingGear: FlagChemistGear
  icon: "JobIconFlagChemist"
  supervisors: job-supervisors-chom
  access:
  - Medical
  - Maintenance
  - Chemistry
  - Cryogenics

# Flagship
# PLEASE RESPECT THE EQUIPMENT ORDER OR I WILL STEAL YOUR NOSE
# equipment: id, head, eyes, ears, mask, neck, outerClothing, jumpsuit, gloves, back, belt, shoes
- type: startingGear
  id: FlagChemistGear
  equipment:
    id: FlagChemistPDA
    head: ClothingHeadHatWhiteCap
    eyes: ClothingEyesFlagGlassesChemical
    ears: ClothingHeadsetFlagMedical
    mask: ClothingMaskFlagSterile
    jumpsuit: ClothingUniformJumpsuitFlagMedicalDoctor
    outerClothing: ClothingOuterCoatFlagLabChemOpened
    gloves: ClothingHandsGlovesFlagNitrile
    back: ClothingBackpackFlagChemistry
    belt: ClothingBeltFlagMedical
    shoes: ClothingShoesFlagColorWhite
