- type: job
  id: MedicalDoctor
  name: job-name-medicaldoctor
  description: job-description-medicaldoctor
  playTimeTracker: JobMedicalDoctor
  setPreference: true
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 #10 hrs
  displayWeight: 80
  startingGear: MedicalDoctorGear
  icon: "JobIconMedicalDoctor"
  supervisors: job-supervisors-chom
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: DoctorDay
    prototype: WehMedipen

- type: startingGear
  id: MedicalDoctorGear
  equipment:
    ears: ClothingHeadsetCommandingOfficer

- type: chameleonOutfit
  id: MedicalDoctorChameleonOutfit
  job: MedicalDoctor
  equipment:
    head: ClothingHeadNurseHat
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    neck: ClothingNeckStethoscope
    outerClothing: ClothingOuterCoatLab
    gloves: ClothingHandsGlovesLatex
