- type: job
  id: FlagBartender
  name: job-name-flag-bartender
  description: job-description-flag-bartender
  playTimeTracker: JobFlagBartender
  requirements:
    - !type:DepartmentTimeRequirement
      department: Service
      time: 0.5h
  startingGear: FlagBartenderGear
  icon: "JobIconFlagBartender"
  supervisors: job-supervisors-oo
  access:
  - Service
  - Maintenance
  - Bar
  extendedAccess:
  - Kitchen
  - Hydroponics

# Flagship
# PLEASE RESPECT THE EQUIPMENT ORDER OR I WILL STEAL YOUR NOSE
# equipment: id, head, eyes, ears, mask, neck, outerClothing, jumpsuit, gloves, back, belt, shoes
- type: startingGear
  id: FlagBartenderGear
  equipment:
    id: FlagBartenderPDA # Flagship
    head: ClothingHeadHatFlagTophat # Flagship
    eyes: ClothingEyesGlassesFlagCheapSunglasses # Flagship
    ears: ClothingHeadsetFlagService # Flagship
    jumpsuit: ClothingUniformJumpsuitFlagBartender # Flagship
    gloves: ClothingHandsGlovesFlagColorWhite # Flagship
    back: ClothingBackpackSatchelFlagLeather # Flagship
    shoes: ClothingShoesBootsFlagLaceup # Flagship
