- type: job
  id: Custodian
  name: job-name-custodian
  description: job-description-custodian
  playTimeTracker: JobCustodian
  setPreference: true
  startingGear: CustodianGear
  icon: "JobIconCustodian"
  supervisors: job-supervisors-oo
  displayWeight: 100
  accessGroups:
  - Command
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: GarbageDay
    prototype: WeaponRevolverInspector

# Flagship
# PLEASE RESPECT THE EQUIPMENT ORDER OR I WILL STEAL YOUR NOSE
# equipment: id, head, eyes, ears, mask, neck, outerClothing, jumpsuit, gloves, back, belt, shoes
- type: startingGear
  id: CustodianGear
  equipment:
    id: CustodianPDA # Flagship
    head: ClothingHeadHatPurpleCap # Flagship
    ears: ClothingHeadsetFlagService # Flagship
    jumpsuit: ClothingUniformJumpsuitCustodian # Flagship
    gloves: ClothingHandsGlovesCustodian # Flagship
    back: ClothingBackpackFlag # Flagship
    belt: ClothingBeltJanitor
    shoes: ClothingShoesGaloshes
