- type: job
  id: MessChef
  name: job-name-mess-chef
  description: job-description-mess-chef
  playTimeTracker: JobMessChef
  setPreference: true
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  startingGear: MessChefGear
  icon: "JobIconMessChef"
  supervisors: job-supervisors-oo
  displayWeight: 80
  accessGroups:
  - Command

# Flagship
# PLEASE RESPECT THE EQUIPMENT ORDER OR I WILL STEAL YOUR NOSE
# equipment: id, head, eyes, ears, mask, neck, outerClothing, jumpsuit, gloves, back, belt, shoes
- type: startingGear
  id: MessChefGear
  equipment:
    id: MessChefPDA # Flagship
    head: ClothingHeadHatFlagChef # Flagship
    ears: ClothingHeadsetFlagService # Flagship
    outerClothing: ClothingOuterApronMessChef
    jumpsuit: ClothingUniformJumpsuitMessChef # Flagship
    back: ClothingBackpack
    belt: ClothingBeltChef
    shoes: ClothingShoesChef
