- type: job
  id: OffDutyCrew
  name: job-name-offduty-crew
  description: job-description-offduty-crew
  playTimeTracker: JobOffDutyCrew
  setPreference: true
  startingGear: OffDutyCrewGear
  supervisors: job-supervisors-oo
  icon: "JobIconOffDutyCrew"
  displayWeight: 10
  accessGroups:
  - Command

# Flagship
# PLEASE RESPECT THE EQUIPMENT ORDER OR I WILL STEAL YOUR NOSE
# equipment: id, head, eyes, ears, mask, neck, outerClothing, jumpsuit, gloves, back, belt, shoes
- type: startingGear
  id: OffDutyCrewGear
  equipment:
    id: OffDutyCrewPDA # Flagship
    ears: ClothingHeadsetFlagShip # Flagship
    jumpsuit: ClothingUniformJumpsuitFlagColorGrey # Flagship
    back: ClothingBackpack
    shoes: ClothingShoesColorBlack
